import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "React Take Home Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  editBookModal,
}: {
  children: React.ReactNode;
  editBookModal: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {editBookModal}
          {children}
        </Providers>
      </body>
    </html>
  );
}
